/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardGrid: typeof import('./src/components/CardGrid/index.vue')['default']
    FeatureList: typeof import('./src/components/PokeCard/FeatureList/index.vue')['default']
    ListGroup: typeof import('./src/components/PokeCard/ListGroup/index.vue')['default']
    PokeCard: typeof import('./src/components/PokeCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
